use serde::{Deserialize, Serialize};

// Define the Match model
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Match {
    pub match_id: String,
    pub short_id: String,
    pub live_battle: bool,
    pub live_admin_name: String,
    pub live_admin_registration_id: String,
    pub last_updated_timestamp: i64,
    pub call_out_timestamp: i64,
    pub response_timestamp: i64,
    pub voting_duration: i32,
    pub a_camp_username: String,
    pub a_camp_video_type: String,
    pub a_camp_video_height: i32,
    pub a_camp_video_width: i32,
    pub a_camp_video_id: String,
    pub a_camp_img_src: String,
    pub a_camp_vid_src: String,
    pub a_camp_instagram: String,
    pub a_camp_vote_count: i32,
    pub a_camp_judge_vote_count: i32,
    pub a_camp_final_vote_count: i32,
    pub a_camp_withdrawn: bool,
    pub a_camp_verified: bool,
    pub rules: String,
    pub responder_reply: String,
    pub b_camp_username: String,
    pub b_camp_video_type: String,
    pub b_camp_video_height: i32,
    pub b_camp_video_width: i32,
    pub b_camp_video_id: String,
    pub b_camp_img_src: String,
    pub b_camp_vid_src: String,
    pub b_camp_instagram: String,
    pub b_camp_vote_count: i32,
    pub b_camp_judge_vote_count: i32,
    pub b_camp_final_vote_count: i32,
    pub b_camp_withdrawn: bool,
    pub b_camp_verified: bool,
    pub judges: Vec<String>,
    pub reporting_sequence: Vec<String>,
    pub closed: bool,
}
